name: Publish Docker Image

on:
  schedule:
    - cron: '15 11 * * *'
  push:
    branches:
      - main
    paths:
      - 'custom-start.sh'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}

    steps:
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Image Update Checker
        id: check
        if: ${{ github.event_name == 'schedule' }}
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: ghcr.io/pi-hole/pihole:latest
          image: ghcr.io/j-pap/pihole:latest
          platforms: linux/amd64,linux/arm64

  build:
    needs: check
    if: ${{ github.event_name != 'schedule' || needs.check.outputs.needs-updating == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Get Latest Release
        id: upstream
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: pi-hole/docker-pi-hole
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.9.2
        with:
          cosign-release: 'v2.5.3'

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and push Docker image
        id: build-and-push
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6.18.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: |
            ghcr.io/j-pap/pihole:latest
            ghcr.io/j-pap/pihole:${{ steps.upstream.outputs.release }}

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.build-and-push.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Verify tags in GHCR
        run: |
          echo "Checking which tags exist for ghcr.io/j-pap/pihole ..."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://ghcr.io/v2/j-pap/pihole/tags/list | jq .
